language: php
services:
  - mysql
php:
  - 5.6
  - hhvm

before_install:
  - cp .env.travis .env
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev
  - mysql -e 'CREATE DATABASE openchat;'
  - mysql -u root  openchat < ./sql/openchat.sql

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v