language: php

php:
  - 5.6
  - hhvm

before_install:
  - cp .env.example .env
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev

script:
  - mkdir -p tests/logs
  - dev ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - dev php vendor/bin/coveralls -v